apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-staging

resources:
  - ../../base

patchesStrategicMerge:
  - patches/replicas.yaml

commonLabels:
  environment: staging

namePrefix: staging-

configMapGenerator:
  - name: app-config
    literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=staging
