apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-base

resources:
  - namespace.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: microservices

commonAnnotations:
  kustomize.toolkit.fluxcd.io/prune: "disabled"
